name: CI Pipeline - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Build Environment
        run: docker --version

      # Step 3: Build Docker image
      - name: Build Docker image
        working-directory: ./
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quick-poll-app:latest .
  

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 5: Push image to Docker Hub
      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/quick-poll-app:latest

      # Step 6: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 7: Log in to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 8: Build, Tag, and Push to Amazon ECR
      - name: Build, Tag, and Push to Amazon ECR
        env:
          AWS_REGION: ap-south-2
          ECR_REPOSITORY: simple-app
          ECR_REGISTRY: 894669428220.dkr.ecr.ap-south-2.amazonaws.com
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/quick-poll-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

